version: '2'

services:
  Ajo_Wallet:    
    container_name: ajowallet
    image: ajowallet
    build: .
    volumes:
      - .:/var/www
    networks:
      - main_network

  database:
    container_name: ajo_db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
        - "3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: "ajouser"
        MYSQL_PASSWORD: "ajorpass"
        MYSQL_DATABASE: "ajo"
    networks:
        - main_network

  redis:
    container_name: ajo_redis
    image: redis
    ports:
        - "6379"
    networks:
        - main_network

networks:
  main_network:
    driver: bridge
